[package]
name = "transaction-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rust_decimal = "1.37.1"
serde = { version = "1.0.219", features = ["derive"] }
csv = "1.3.1"

[dev-dependencies]
tempfile = "3.19.1"
itertools = "0.14.0"
